services:
  github-weekly-ai-bot:
     build: .
     container_name: github-weekly-ai-bot
     env_file:
        - .env
     volumes:
        - .:/app
        - /app/node_modules
     command: npm run start:api
     ports:
        - "3000:3000"
